
package com.chathurangaonline.samples.jax.ws.jaxb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeServiceImpl", targetNamespace = "http://jaxb.ws.jax.samples.chathurangaonline.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.chathurangaonline.samples.jax.ws.jaxb.Employee
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://jaxb.ws.jax.samples.chathurangaonline.com/EmployeeServiceImpl/findEmployeeByIdRequest", output = "http://jaxb.ws.jax.samples.chathurangaonline.com/EmployeeServiceImpl/findEmployeeByIdResponse")
    public Employee findEmployeeById(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.chathurangaonline.samples.jax.ws.jaxb.Employee
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://jaxb.ws.jax.samples.chathurangaonline.com/EmployeeServiceImpl/createRequest", output = "http://jaxb.ws.jax.samples.chathurangaonline.com/EmployeeServiceImpl/createResponse")
    public Employee create(
        @WebParam(name = "arg0", partName = "arg0")
        Employee arg0);

}
